apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - command:
            - /shared/argocd-dex
            - rundex
          name: dex
      initContainers:
        - command:
            - cp
            - -n
            - /usr/local/bin/argocd-dex
            - /shared
          name: copyutil
